server:
  port: 9099

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: customer-client-service
  sleuth:
    enabled: true
    web:
      skipPattern: (^cleanup.*)
    sampler:
      percentage: 1.0

logging:
  level:
    org.exampledriven.eureka: DEBUG