- hosts: localhost
  vars:
    code_path: '/Users/Shared/Jenkins/Home/workspace/tmp/pcf-poc-greetings-0.1.0.jar' 
  tasks:      
    - maven_artifact:
        group_id: com.hsbc.eqfin
        artifact_id: pcf-poc-greetings
        version: 0.1.0
        repository_url: "http://localhost:8081/nexus/content/repositories/releases/"
        extension: jar
        username: admin
        password: admin123
        dest: "/Users/Shared/Jenkins/Home/workspace/tmp/pcf-poc-greetings-0.1.0.jar"
        state: present
    - name: Login  to Cloud Foundry
      shell: /usr/local/bin/cf login -a https://api.run.pivotal.io -u srefson@gmail.com -o Sysetchred -s development`
    - name: deploy app to cloud foundry
      shell: /usr/local/bin/cf push pcf-poc-deployment  -p {{code_path}}

      